# This example uses a host mounted directory that is created/used relative to this
# location of this compose file.

version: '3.4'

services:
  mc:
    container_name: server
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: normal
      TZ: "America/Sao_Paulo"
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
  ngrok:
    container_name: ngrok-tunnel
    image: crisdias/ngrok-minecraft
    network_mode: service:mc
    environment:
      # check https://medium.com/@oliverbravery/publically-exposing-tcp-ports-with-static-url-without-port-forwarding-9ddd32ca2726 for instructions
      - NGROK_AUTHTOKEN=<YOUR_AUTHTOKEN>
      - CLOUDFLARE_ZONE_ID=<YOUR_ZONE_ID>
      - CLOUDFLARE_DNS_RECORD_ID=<YOUR_DNS_RECORD_ID>
      - CLOUDFLARE_API_TOKEN=<YOUR_API_TOKEN>
      - MINECRAFT_PORT=25565
    restart: unless-stopped
    depends_on:
      - mc
